name: Build and Deploy AsciiDoctor to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Asciidoctor
      run: sudo apt-get update && sudo apt-get install -y asciidoctor

    - name: Build AsciiDoc files
      run: |
        mkdir -p build
        asciidoctor --attribute=nofooter -D build *.adoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
